# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/gh200-trading-system

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/gh200-trading-system

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/gh200-trading-system/CMakeFiles /home/ubuntu/gh200-trading-system//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/gh200-trading-system/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named trading_core

# Build rule for target.
trading_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trading_core
.PHONY : trading_core

# fast build rule for target.
trading_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/build
.PHONY : trading_core/fast

#=============================================================================
# Target rules for targets named monitoring

# Build rule for target.
monitoring: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monitoring
.PHONY : monitoring

# fast build rule for target.
monitoring/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monitoring.dir/build.make CMakeFiles/monitoring.dir/build
.PHONY : monitoring/fast

#=============================================================================
# Target rules for targets named trading_system

# Build rule for target.
trading_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trading_system
.PHONY : trading_system

# fast build rule for target.
trading_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system.dir/build.make CMakeFiles/trading_system.dir/build
.PHONY : trading_system/fast

#=============================================================================
# Target rules for targets named polygon_snapshot_example

# Build rule for target.
polygon_snapshot_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 polygon_snapshot_example
.PHONY : polygon_snapshot_example

# fast build rule for target.
polygon_snapshot_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_snapshot_example.dir/build.make CMakeFiles/polygon_snapshot_example.dir/build
.PHONY : polygon_snapshot_example/fast

#=============================================================================
# Target rules for targets named model_trainer

# Build rule for target.
model_trainer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model_trainer
.PHONY : model_trainer

# fast build rule for target.
model_trainer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model_trainer.dir/build.make CMakeFiles/model_trainer.dir/build
.PHONY : model_trainer/fast

examples/polygon_snapshot_example.o: examples/polygon_snapshot_example.cpp.o
.PHONY : examples/polygon_snapshot_example.o

# target to build an object file
examples/polygon_snapshot_example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_snapshot_example.dir/build.make CMakeFiles/polygon_snapshot_example.dir/examples/polygon_snapshot_example.cpp.o
.PHONY : examples/polygon_snapshot_example.cpp.o

examples/polygon_snapshot_example.i: examples/polygon_snapshot_example.cpp.i
.PHONY : examples/polygon_snapshot_example.i

# target to preprocess a source file
examples/polygon_snapshot_example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_snapshot_example.dir/build.make CMakeFiles/polygon_snapshot_example.dir/examples/polygon_snapshot_example.cpp.i
.PHONY : examples/polygon_snapshot_example.cpp.i

examples/polygon_snapshot_example.s: examples/polygon_snapshot_example.cpp.s
.PHONY : examples/polygon_snapshot_example.s

# target to generate assembly for a file
examples/polygon_snapshot_example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_snapshot_example.dir/build.make CMakeFiles/polygon_snapshot_example.dir/examples/polygon_snapshot_example.cpp.s
.PHONY : examples/polygon_snapshot_example.cpp.s

src/common/config.o: src/common/config.cpp.o
.PHONY : src/common/config.o

# target to build an object file
src/common/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/common/config.cpp.o
.PHONY : src/common/config.cpp.o

src/common/config.i: src/common/config.cpp.i
.PHONY : src/common/config.i

# target to preprocess a source file
src/common/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/common/config.cpp.i
.PHONY : src/common/config.cpp.i

src/common/config.s: src/common/config.cpp.s
.PHONY : src/common/config.s

# target to generate assembly for a file
src/common/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/common/config.cpp.s
.PHONY : src/common/config.cpp.s

src/common/logging.o: src/common/logging.cpp.o
.PHONY : src/common/logging.o

# target to build an object file
src/common/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/common/logging.cpp.o
.PHONY : src/common/logging.cpp.o

src/common/logging.i: src/common/logging.cpp.i
.PHONY : src/common/logging.i

# target to preprocess a source file
src/common/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/common/logging.cpp.i
.PHONY : src/common/logging.cpp.i

src/common/logging.s: src/common/logging.cpp.s
.PHONY : src/common/logging.s

# target to generate assembly for a file
src/common/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/common/logging.cpp.s
.PHONY : src/common/logging.cpp.s

src/data/market_data.o: src/data/market_data.cpp.o
.PHONY : src/data/market_data.o

# target to build an object file
src/data/market_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/market_data.cpp.o
.PHONY : src/data/market_data.cpp.o

src/data/market_data.i: src/data/market_data.cpp.i
.PHONY : src/data/market_data.i

# target to preprocess a source file
src/data/market_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/market_data.cpp.i
.PHONY : src/data/market_data.cpp.i

src/data/market_data.s: src/data/market_data.cpp.s
.PHONY : src/data/market_data.s

# target to generate assembly for a file
src/data/market_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/market_data.cpp.s
.PHONY : src/data/market_data.cpp.s

src/data/polygon_client.o: src/data/polygon_client.cpp.o
.PHONY : src/data/polygon_client.o

# target to build an object file
src/data/polygon_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/polygon_client.cpp.o
.PHONY : src/data/polygon_client.cpp.o

src/data/polygon_client.i: src/data/polygon_client.cpp.i
.PHONY : src/data/polygon_client.i

# target to preprocess a source file
src/data/polygon_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/polygon_client.cpp.i
.PHONY : src/data/polygon_client.cpp.i

src/data/polygon_client.s: src/data/polygon_client.cpp.s
.PHONY : src/data/polygon_client.s

# target to generate assembly for a file
src/data/polygon_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/polygon_client.cpp.s
.PHONY : src/data/polygon_client.cpp.s

src/data/rest_client.o: src/data/rest_client.cpp.o
.PHONY : src/data/rest_client.o

# target to build an object file
src/data/rest_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/rest_client.cpp.o
.PHONY : src/data/rest_client.cpp.o

src/data/rest_client.i: src/data/rest_client.cpp.i
.PHONY : src/data/rest_client.i

# target to preprocess a source file
src/data/rest_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/rest_client.cpp.i
.PHONY : src/data/rest_client.cpp.i

src/data/rest_client.s: src/data/rest_client.cpp.s
.PHONY : src/data/rest_client.s

# target to generate assembly for a file
src/data/rest_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/rest_client.cpp.s
.PHONY : src/data/rest_client.cpp.s

src/data/websocket_client.o: src/data/websocket_client.cpp.o
.PHONY : src/data/websocket_client.o

# target to build an object file
src/data/websocket_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/websocket_client.cpp.o
.PHONY : src/data/websocket_client.cpp.o

src/data/websocket_client.i: src/data/websocket_client.cpp.i
.PHONY : src/data/websocket_client.i

# target to preprocess a source file
src/data/websocket_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/websocket_client.cpp.i
.PHONY : src/data/websocket_client.cpp.i

src/data/websocket_client.s: src/data/websocket_client.cpp.s
.PHONY : src/data/websocket_client.s

# target to generate assembly for a file
src/data/websocket_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/data/websocket_client.cpp.s
.PHONY : src/data/websocket_client.cpp.s

src/execution/broker_client.o: src/execution/broker_client.cpp.o
.PHONY : src/execution/broker_client.o

# target to build an object file
src/execution/broker_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/execution/broker_client.cpp.o
.PHONY : src/execution/broker_client.cpp.o

src/execution/broker_client.i: src/execution/broker_client.cpp.i
.PHONY : src/execution/broker_client.i

# target to preprocess a source file
src/execution/broker_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/execution/broker_client.cpp.i
.PHONY : src/execution/broker_client.cpp.i

src/execution/broker_client.s: src/execution/broker_client.cpp.s
.PHONY : src/execution/broker_client.s

# target to generate assembly for a file
src/execution/broker_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/execution/broker_client.cpp.s
.PHONY : src/execution/broker_client.cpp.s

src/execution/execution_engine.o: src/execution/execution_engine.cpp.o
.PHONY : src/execution/execution_engine.o

# target to build an object file
src/execution/execution_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/execution/execution_engine.cpp.o
.PHONY : src/execution/execution_engine.cpp.o

src/execution/execution_engine.i: src/execution/execution_engine.cpp.i
.PHONY : src/execution/execution_engine.i

# target to preprocess a source file
src/execution/execution_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/execution/execution_engine.cpp.i
.PHONY : src/execution/execution_engine.cpp.i

src/execution/execution_engine.s: src/execution/execution_engine.cpp.s
.PHONY : src/execution/execution_engine.s

# target to generate assembly for a file
src/execution/execution_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/execution/execution_engine.cpp.s
.PHONY : src/execution/execution_engine.cpp.s

src/execution/order.o: src/execution/order.cpp.o
.PHONY : src/execution/order.o

# target to build an object file
src/execution/order.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/execution/order.cpp.o
.PHONY : src/execution/order.cpp.o

src/execution/order.i: src/execution/order.cpp.i
.PHONY : src/execution/order.i

# target to preprocess a source file
src/execution/order.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/execution/order.cpp.i
.PHONY : src/execution/order.cpp.i

src/execution/order.s: src/execution/order.cpp.s
.PHONY : src/execution/order.s

# target to generate assembly for a file
src/execution/order.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/execution/order.cpp.s
.PHONY : src/execution/order.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system.dir/build.make CMakeFiles/trading_system.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system.dir/build.make CMakeFiles/trading_system.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_system.dir/build.make CMakeFiles/trading_system.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ml/axial_attention_model.o: src/ml/axial_attention_model.cpp.o
.PHONY : src/ml/axial_attention_model.o

# target to build an object file
src/ml/axial_attention_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/axial_attention_model.cpp.o
.PHONY : src/ml/axial_attention_model.cpp.o

src/ml/axial_attention_model.i: src/ml/axial_attention_model.cpp.i
.PHONY : src/ml/axial_attention_model.i

# target to preprocess a source file
src/ml/axial_attention_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/axial_attention_model.cpp.i
.PHONY : src/ml/axial_attention_model.cpp.i

src/ml/axial_attention_model.s: src/ml/axial_attention_model.cpp.s
.PHONY : src/ml/axial_attention_model.s

# target to generate assembly for a file
src/ml/axial_attention_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/axial_attention_model.cpp.s
.PHONY : src/ml/axial_attention_model.cpp.s

src/ml/exit_optimization.o: src/ml/exit_optimization.cpp.o
.PHONY : src/ml/exit_optimization.o

# target to build an object file
src/ml/exit_optimization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/exit_optimization.cpp.o
.PHONY : src/ml/exit_optimization.cpp.o

src/ml/exit_optimization.i: src/ml/exit_optimization.cpp.i
.PHONY : src/ml/exit_optimization.i

# target to preprocess a source file
src/ml/exit_optimization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/exit_optimization.cpp.i
.PHONY : src/ml/exit_optimization.cpp.i

src/ml/exit_optimization.s: src/ml/exit_optimization.cpp.s
.PHONY : src/ml/exit_optimization.s

# target to generate assembly for a file
src/ml/exit_optimization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/exit_optimization.cpp.s
.PHONY : src/ml/exit_optimization.cpp.s

src/ml/gbdt_model.o: src/ml/gbdt_model.cpp.o
.PHONY : src/ml/gbdt_model.o

# target to build an object file
src/ml/gbdt_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/gbdt_model.cpp.o
.PHONY : src/ml/gbdt_model.cpp.o

src/ml/gbdt_model.i: src/ml/gbdt_model.cpp.i
.PHONY : src/ml/gbdt_model.i

# target to preprocess a source file
src/ml/gbdt_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/gbdt_model.cpp.i
.PHONY : src/ml/gbdt_model.cpp.i

src/ml/gbdt_model.s: src/ml/gbdt_model.cpp.s
.PHONY : src/ml/gbdt_model.s

# target to generate assembly for a file
src/ml/gbdt_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/gbdt_model.cpp.s
.PHONY : src/ml/gbdt_model.cpp.s

src/ml/inference.o: src/ml/inference.cpp.o
.PHONY : src/ml/inference.o

# target to build an object file
src/ml/inference.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/inference.cpp.o
.PHONY : src/ml/inference.cpp.o

src/ml/inference.i: src/ml/inference.cpp.i
.PHONY : src/ml/inference.i

# target to preprocess a source file
src/ml/inference.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/inference.cpp.i
.PHONY : src/ml/inference.cpp.i

src/ml/inference.s: src/ml/inference.cpp.s
.PHONY : src/ml/inference.s

# target to generate assembly for a file
src/ml/inference.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/inference.cpp.s
.PHONY : src/ml/inference.cpp.s

src/ml/lstm_gru_model.o: src/ml/lstm_gru_model.cpp.o
.PHONY : src/ml/lstm_gru_model.o

# target to build an object file
src/ml/lstm_gru_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/lstm_gru_model.cpp.o
.PHONY : src/ml/lstm_gru_model.cpp.o

src/ml/lstm_gru_model.i: src/ml/lstm_gru_model.cpp.i
.PHONY : src/ml/lstm_gru_model.i

# target to preprocess a source file
src/ml/lstm_gru_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/lstm_gru_model.cpp.i
.PHONY : src/ml/lstm_gru_model.cpp.i

src/ml/lstm_gru_model.s: src/ml/lstm_gru_model.cpp.s
.PHONY : src/ml/lstm_gru_model.s

# target to generate assembly for a file
src/ml/lstm_gru_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/lstm_gru_model.cpp.s
.PHONY : src/ml/lstm_gru_model.cpp.s

src/ml/market_snapshot_processor.o: src/ml/market_snapshot_processor.cpp.o
.PHONY : src/ml/market_snapshot_processor.o

# target to build an object file
src/ml/market_snapshot_processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/market_snapshot_processor.cpp.o
.PHONY : src/ml/market_snapshot_processor.cpp.o

src/ml/market_snapshot_processor.i: src/ml/market_snapshot_processor.cpp.i
.PHONY : src/ml/market_snapshot_processor.i

# target to preprocess a source file
src/ml/market_snapshot_processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/market_snapshot_processor.cpp.i
.PHONY : src/ml/market_snapshot_processor.cpp.i

src/ml/market_snapshot_processor.s: src/ml/market_snapshot_processor.cpp.s
.PHONY : src/ml/market_snapshot_processor.s

# target to generate assembly for a file
src/ml/market_snapshot_processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/market_snapshot_processor.cpp.s
.PHONY : src/ml/market_snapshot_processor.cpp.s

src/ml/model.o: src/ml/model.cpp.o
.PHONY : src/ml/model.o

# target to build an object file
src/ml/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/model.cpp.o
.PHONY : src/ml/model.cpp.o

src/ml/model.i: src/ml/model.cpp.i
.PHONY : src/ml/model.i

# target to preprocess a source file
src/ml/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/model.cpp.i
.PHONY : src/ml/model.cpp.i

src/ml/model.s: src/ml/model.cpp.s
.PHONY : src/ml/model.s

# target to generate assembly for a file
src/ml/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/model.cpp.s
.PHONY : src/ml/model.cpp.s

src/ml/model_trainer.o: src/ml/model_trainer.cpp.o
.PHONY : src/ml/model_trainer.o

# target to build an object file
src/ml/model_trainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/model_trainer.cpp.o
.PHONY : src/ml/model_trainer.cpp.o

src/ml/model_trainer.i: src/ml/model_trainer.cpp.i
.PHONY : src/ml/model_trainer.i

# target to preprocess a source file
src/ml/model_trainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/model_trainer.cpp.i
.PHONY : src/ml/model_trainer.cpp.i

src/ml/model_trainer.s: src/ml/model_trainer.cpp.s
.PHONY : src/ml/model_trainer.s

# target to generate assembly for a file
src/ml/model_trainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/ml/model_trainer.cpp.s
.PHONY : src/ml/model_trainer.cpp.s

src/ml/model_trainer_main.o: src/ml/model_trainer_main.cpp.o
.PHONY : src/ml/model_trainer_main.o

# target to build an object file
src/ml/model_trainer_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model_trainer.dir/build.make CMakeFiles/model_trainer.dir/src/ml/model_trainer_main.cpp.o
.PHONY : src/ml/model_trainer_main.cpp.o

src/ml/model_trainer_main.i: src/ml/model_trainer_main.cpp.i
.PHONY : src/ml/model_trainer_main.i

# target to preprocess a source file
src/ml/model_trainer_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model_trainer.dir/build.make CMakeFiles/model_trainer.dir/src/ml/model_trainer_main.cpp.i
.PHONY : src/ml/model_trainer_main.cpp.i

src/ml/model_trainer_main.s: src/ml/model_trainer_main.cpp.s
.PHONY : src/ml/model_trainer_main.s

# target to generate assembly for a file
src/ml/model_trainer_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/model_trainer.dir/build.make CMakeFiles/model_trainer.dir/src/ml/model_trainer_main.cpp.s
.PHONY : src/ml/model_trainer_main.cpp.s

src/monitoring/metrics_publisher.o: src/monitoring/metrics_publisher.cpp.o
.PHONY : src/monitoring/metrics_publisher.o

# target to build an object file
src/monitoring/metrics_publisher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monitoring.dir/build.make CMakeFiles/monitoring.dir/src/monitoring/metrics_publisher.cpp.o
.PHONY : src/monitoring/metrics_publisher.cpp.o

src/monitoring/metrics_publisher.i: src/monitoring/metrics_publisher.cpp.i
.PHONY : src/monitoring/metrics_publisher.i

# target to preprocess a source file
src/monitoring/metrics_publisher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monitoring.dir/build.make CMakeFiles/monitoring.dir/src/monitoring/metrics_publisher.cpp.i
.PHONY : src/monitoring/metrics_publisher.cpp.i

src/monitoring/metrics_publisher.s: src/monitoring/metrics_publisher.cpp.s
.PHONY : src/monitoring/metrics_publisher.s

# target to generate assembly for a file
src/monitoring/metrics_publisher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/monitoring.dir/build.make CMakeFiles/monitoring.dir/src/monitoring/metrics_publisher.cpp.s
.PHONY : src/monitoring/metrics_publisher.cpp.s

src/risk/risk_manager.o: src/risk/risk_manager.cpp.o
.PHONY : src/risk/risk_manager.o

# target to build an object file
src/risk/risk_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/risk/risk_manager.cpp.o
.PHONY : src/risk/risk_manager.cpp.o

src/risk/risk_manager.i: src/risk/risk_manager.cpp.i
.PHONY : src/risk/risk_manager.i

# target to preprocess a source file
src/risk/risk_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/risk/risk_manager.cpp.i
.PHONY : src/risk/risk_manager.cpp.i

src/risk/risk_manager.s: src/risk/risk_manager.cpp.s
.PHONY : src/risk/risk_manager.s

# target to generate assembly for a file
src/risk/risk_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trading_core.dir/build.make CMakeFiles/trading_core.dir/src/risk/risk_manager.cpp.s
.PHONY : src/risk/risk_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... model_trainer"
	@echo "... monitoring"
	@echo "... polygon_snapshot_example"
	@echo "... trading_core"
	@echo "... trading_system"
	@echo "... examples/polygon_snapshot_example.o"
	@echo "... examples/polygon_snapshot_example.i"
	@echo "... examples/polygon_snapshot_example.s"
	@echo "... src/common/config.o"
	@echo "... src/common/config.i"
	@echo "... src/common/config.s"
	@echo "... src/common/logging.o"
	@echo "... src/common/logging.i"
	@echo "... src/common/logging.s"
	@echo "... src/data/market_data.o"
	@echo "... src/data/market_data.i"
	@echo "... src/data/market_data.s"
	@echo "... src/data/polygon_client.o"
	@echo "... src/data/polygon_client.i"
	@echo "... src/data/polygon_client.s"
	@echo "... src/data/rest_client.o"
	@echo "... src/data/rest_client.i"
	@echo "... src/data/rest_client.s"
	@echo "... src/data/websocket_client.o"
	@echo "... src/data/websocket_client.i"
	@echo "... src/data/websocket_client.s"
	@echo "... src/execution/broker_client.o"
	@echo "... src/execution/broker_client.i"
	@echo "... src/execution/broker_client.s"
	@echo "... src/execution/execution_engine.o"
	@echo "... src/execution/execution_engine.i"
	@echo "... src/execution/execution_engine.s"
	@echo "... src/execution/order.o"
	@echo "... src/execution/order.i"
	@echo "... src/execution/order.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ml/axial_attention_model.o"
	@echo "... src/ml/axial_attention_model.i"
	@echo "... src/ml/axial_attention_model.s"
	@echo "... src/ml/exit_optimization.o"
	@echo "... src/ml/exit_optimization.i"
	@echo "... src/ml/exit_optimization.s"
	@echo "... src/ml/gbdt_model.o"
	@echo "... src/ml/gbdt_model.i"
	@echo "... src/ml/gbdt_model.s"
	@echo "... src/ml/inference.o"
	@echo "... src/ml/inference.i"
	@echo "... src/ml/inference.s"
	@echo "... src/ml/lstm_gru_model.o"
	@echo "... src/ml/lstm_gru_model.i"
	@echo "... src/ml/lstm_gru_model.s"
	@echo "... src/ml/market_snapshot_processor.o"
	@echo "... src/ml/market_snapshot_processor.i"
	@echo "... src/ml/market_snapshot_processor.s"
	@echo "... src/ml/model.o"
	@echo "... src/ml/model.i"
	@echo "... src/ml/model.s"
	@echo "... src/ml/model_trainer.o"
	@echo "... src/ml/model_trainer.i"
	@echo "... src/ml/model_trainer.s"
	@echo "... src/ml/model_trainer_main.o"
	@echo "... src/ml/model_trainer_main.i"
	@echo "... src/ml/model_trainer_main.s"
	@echo "... src/monitoring/metrics_publisher.o"
	@echo "... src/monitoring/metrics_publisher.i"
	@echo "... src/monitoring/metrics_publisher.s"
	@echo "... src/risk/risk_manager.o"
	@echo "... src/risk/risk_manager.i"
	@echo "... src/risk/risk_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

