
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/ubuntu/.local/lib/python3.10/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.8.0-1013-nvidia-64k - aarch64
...
